name: Automated Design Smell Detection & Refactoring

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  detect_and_refactor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests gitpython pygithub

      - name: Run design smell detection and refactoring
        env:
          GITHUB_TOKEN: ${{ secrets.CLASS_TOKEN }}
          HF_API_KEY: ${{ secrets.HUGGING_TOKEN }}
        run: python check_design_smells.py  # Ensure your main script is named `script.py`
