# .github/workflows/git.yml

name: Refactor Code and Create PR

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  refactor-and-pr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: master  # The branch to check out

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Step 4: Run the refactoring script
    - name: Refactor code
      run: |
        python check_design_smells.py  # No need to pass any arguments

    # Step 5: Commit changes
    - name: Commit changes
      run: |
        git config --global user.name "praveenkumar911"
        git config --global user.email "praveenkumarpalaboyina@gmail.com"
        git add .
        git commit -m "Refactor code using LLM" || echo "No changes to commit"

    # Step 6: Push changes to a new branch
    - name: Push changes to new branch
      run: |
        git checkout -b refactor-branch
        git push origin refactor-branch

    # Step 7: Create a pull request
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Refactor Code Using LLM"
        body: "Automated refactoring of code using LLM."
        base: master
        branch: refactor-branch
