name: Design Smell Detection and Fix Workflow

on:
  push:
    branches:
      - main

jobs:
  detect-and-fix-design-smells:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install libcst

      - name: Detect and Fix Design Smells
        run: |
          python detect_and_fix_smells.py

      - name: Create New Branch
        run: |
          git config user.name "praveenkumar911"
          git config user.email "praveenkumarpalaboyina@gmail.com"
          git checkout -b design-smell-fixes

      - name: Commit and Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.CLASS_TOKEN }}@github.com/praveenkumar911/SE-reader-web.git
          git add .
          git commit -m "Automated fixes for design smells"
          git push origin design-smell-fixes

      - name: Open Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Automated Fixes for Design Smells"
          pr_body: "This PR contains automated fixes for detected design smells."
          github_token: ${{ secrets.CLASS_TOKEN }}
